package it.keybeeproject.keybee.model;

import java.util.ArrayList;

/**
 * Created by c161 on 20/09/16.
 */
public class EmojiHobies {

	public static final String BOX = "\u20e3";

	public static ArrayList<Emoji> getEmojies() {
		ArrayList<Emoji> emojies = new ArrayList<>();
		emojies.add(Emoji.fromString(("\ud83c\udf83"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udf84"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udf86"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udf87"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\udde8"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\u2728"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udf88"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udf89"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udf8a"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udf8b"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udf8d"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udf8e"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udf8f"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udf90"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udf91"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\udde7"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83c\udf80"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udf81"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udf97\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udf9f\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udfab"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udf96\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udfc6"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udfc5"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\udd47"),false,false,false,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\udd48"),false,false,false,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\udd49"),false,false,false,true,true,true));
		emojies.add(Emoji.fromString(("\u26bd"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\u26be"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\udd4e"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83c\udfc0"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udfd0"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udfc8"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udfc9"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udfbe"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\udd4f"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83c\udfb3"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udfcf"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udfd1"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udfd2"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\udd4d"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83c\udfd3"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udff8"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\udd4a"),false,false,false,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\udd4b"),false,false,false,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\udd45"),false,false,false,true,true,true));
		emojies.add(Emoji.fromString(("\u26f3"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\u26f8\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udfa3"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\udd3f"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83c\udfbd"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udfbf"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udef7"),false,false,false,false,true,true));
		emojies.add(Emoji.fromString(("\ud83e\udd4c"),false,false,false,false,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udfaf"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\ude80"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83e\ude81"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83c\udfb1"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udd2e"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\ude84"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83e\uddff"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83c\udfae"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udd79\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udfb0"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udfb2"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\udde9"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83e\uddf8"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83e\ude85"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83e\ude86"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\u2660\ufe0f"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\u2665\ufe0f"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\u2666\ufe0f"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\u2663\ufe0f"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\u265f\ufe0f"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83c\udccf"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udc04"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udfb4"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udfad"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\uddbc\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udfa8"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\uddf5"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83e\udea1"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83e\uddf6"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83e\udea2"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83d\udc53"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udd76\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\udd7d"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83e\udd7c"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83e\uddba"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83d\udc54"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udc55"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udc56"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\udde3"),false,false,false,false,true,true));
		emojies.add(Emoji.fromString(("\ud83e\udde4"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83e\udde5"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83e\udde6"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83d\udc57"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udc58"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\udd7b"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83e\ude71"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83e\ude72"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83e\ude73"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83d\udc59"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udc5a"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udc5b"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udc5c"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udc5d"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udecd\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udf92"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\ude74"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83d\udc5e"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udc5f"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\udd7e"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83e\udd7f"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83d\udc60"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udc61"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\ude70"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83d\udc62"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udc51"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udc52"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udfa9"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udf93"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\udde2"),false,false,false,false,true,true));
		emojies.add(Emoji.fromString(("\ud83e\ude96"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\u26d1\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcff"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udc84"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udc8d"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udc8e"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udd07"),false,false,true,true,true,true));
		//emojies.add(Emoji.fromString(("\ud83d\udd08"),true,true,true,true,true,true));
		//emojies.add(Emoji.fromString(("\ud83d\udd09"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udd0a"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udce2"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udce3"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcef"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udd14"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udd15"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udfbc"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udfb5"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udfb6"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udf99\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udf9a\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udf9b\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udfa4"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udfa7"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcfb"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udfb7"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\ude97"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83c\udfb8"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udfb9"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udfba"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udfbb"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\ude95"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83e\udd41"),false,false,false,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\ude98"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83d\udcf1"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcf2"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\u260e\ufe0f"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcde"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcdf"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udce0"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udd0b"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udd0c"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcbb"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udda5\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udda8\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\u2328\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\uddb1\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\uddb2\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcbd"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcbe"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcbf"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcc0"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\uddee"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83c\udfa5"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udf9e\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcfd\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udfac"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcfa"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcf7"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcf8"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcf9"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcfc"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udd0d"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udd0e"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udd6f\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udca1"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udd26"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udfee"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\ude94"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83d\udcd4"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcd5"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcd6"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcd7"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcd8"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcd9"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcda"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcd3"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcd2"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcc3"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcdc"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcc4"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcf0"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\uddde\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcd1"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udd16"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83c\udff7\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcb0"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\ude99"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83d\udcb4"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcb5"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcb6"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcb7"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcb8"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcb3"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\uddfe"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83d\udcb9"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\u2709\ufe0f"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udce7"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udce8"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udce9"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udce4"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udce5"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udce6"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udceb"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcea"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcec"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udced"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcee"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\uddf3\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\u270f\ufe0f"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\u2712\ufe0f"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udd8b\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udd8a\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udd8c\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udd8d\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcdd"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcbc"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcc1"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcc2"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\uddc2\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcc5"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcc6"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\uddd2\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\uddd3\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcc7"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcc8"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcc9"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcca"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udccb"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udccc"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udccd"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcce"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udd87\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udccf"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udcd0"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\u2702\ufe0f"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\uddc3\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\uddc4\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\uddd1\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udd12"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udd13"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udd0f"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udd10"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udd11"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udddd\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udd28"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\ude93"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\u26cf\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\u2692\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udee0\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udde1\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\u2694\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udd2b"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\ude83"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83c\udff9"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udee1\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\ude9a"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83d\udd27"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\ude9b"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83d\udd29"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\u2699\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udddc\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\u2696\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\uddaf"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83d\udd17"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\u26d3\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\ude9d"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83e\uddf0"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83e\uddf2"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83e\ude9c"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\u2697\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\uddea"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83e\uddeb"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83e\uddec"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83d\udd2c"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udd2d"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udce1"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udc89"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\ude78"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83d\udc8a"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\ude79"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83e\ude7a"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83d\udeaa"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\uded7"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83e\ude9e"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83e\ude9f"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83d\udecf\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udecb\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\ude91"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83d\udebd"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\udea0"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83d\udebf"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udec1"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\udea4"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83e\ude92"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83e\uddf4"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83e\uddf7"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83e\uddf9"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83e\uddfa"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83e\uddfb"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83e\udea3"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83e\uddfc"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83e\udea5"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83e\uddfd"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83e\uddef"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\ud83d\uded2"),false,false,false,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\udeac"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\u26b0\ufe0f"),false,false,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\udea6"),false,false,false,false,false,true));
		emojies.add(Emoji.fromString(("\u26b1\ufe0f"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83d\uddff"),true,true,true,true,true,true));
		emojies.add(Emoji.fromString(("\ud83e\udea7"),false,false,false,false,false,true));


		/*emojies.add(Emoji.fromString("\u0031" + BOX, false));
		emojies.add(Emoji.fromString("\u0032" + BOX, false));
		emojies.add(Emoji.fromString("\u0033" + BOX, false));
		emojies.add(Emoji.fromString("\u0034" + BOX, false));

		emojies.add(Emoji.fromString("\u0035" + BOX, false));

		emojies.add(Emoji.fromString("\u0036" + BOX, false));
		emojies.add(Emoji.fromString("\u0037" + BOX, false));
		emojies.add(Emoji.fromString("\u0038" + BOX, false));
		emojies.add(Emoji.fromString("\u0039" + BOX, false));
		emojies.add(Emoji.fromString("\u0030" + BOX, false));
		emojies.add(Emoji.fromCodePoint(0x1f51f, true));
		emojies.add(Emoji.fromCodePoint(0x1f522, true));
		emojies.add(Emoji.fromString("\u0023" + BOX, false));
		emojies.add(Emoji.fromCodePoint(0x1f523, true));
		emojies.add(Emoji.fromChar((char) 0x2b06, true));
		emojies.add(Emoji.fromChar((char) 0x2b07, true));
		emojies.add(Emoji.fromChar((char) 0x2b05, true));
		emojies.add(Emoji.fromChar((char) 0x27a1, true));
		emojies.add(Emoji.fromCodePoint(0x1f520, true));
		emojies.add(Emoji.fromCodePoint(0x1f521, true));
		emojies.add(Emoji.fromCodePoint(0x1f524, true));
		emojies.add(Emoji.fromChar((char) 0x2197, true));
		emojies.add(Emoji.fromChar((char) 0x2196, true));
		emojies.add(Emoji.fromChar((char) 0x2198, true));
		emojies.add(Emoji.fromChar((char) 0x2199, true));
		emojies.add(Emoji.fromChar((char) 0x2194, true));
		emojies.add(Emoji.fromChar((char) 0x2195, true));
		emojies.add(Emoji.fromCodePoint(0x1f504, false));
		emojies.add(Emoji.fromChar((char) 0x25c0, true));
		emojies.add(Emoji.fromChar((char) 0x25b6, true));
		emojies.add(Emoji.fromCodePoint(0x1f53c, true));
		emojies.add(Emoji.fromCodePoint(0x1f53d, true));
		emojies.add(Emoji.fromChar((char) 0x21a9, true));
		emojies.add(Emoji.fromChar((char) 0x21aa, true));
		emojies.add(Emoji.fromChar((char) 0x2139, true));
		emojies.add(Emoji.fromChar((char) 0x23ea, true));
		emojies.add(Emoji.fromChar((char) 0x23e9, true));
		emojies.add(Emoji.fromChar((char) 0x23eb, true));
		emojies.add(Emoji.fromChar((char) 0x23ec, true));
		emojies.add(Emoji.fromChar((char) 0x2935, true));
		emojies.add(Emoji.fromChar((char) 0x2934, true));
		emojies.add(Emoji.fromCodePoint(0x1f197, true));
		emojies.add(Emoji.fromCodePoint(0x1f500, false));
		emojies.add(Emoji.fromCodePoint(0x1f501, false));
		emojies.add(Emoji.fromCodePoint(0x1f502, false));
		emojies.add(Emoji.fromCodePoint(0x1f195, true));
		emojies.add(Emoji.fromCodePoint(0x1f199, true));
		emojies.add(Emoji.fromCodePoint(0x1f192, true));
		emojies.add(Emoji.fromCodePoint(0x1f193, true));
		emojies.add(Emoji.fromCodePoint(0x1f196, true));
		emojies.add(Emoji.fromCodePoint(0x1f4f6, true));
		emojies.add(Emoji.fromCodePoint(0x1f3a6, true));
		emojies.add(Emoji.fromCodePoint(0x1f201, true));
		emojies.add(Emoji.fromCodePoint(0x1f22f, true));
		emojies.add(Emoji.fromCodePoint(0x1f233, true));
		emojies.add(Emoji.fromCodePoint(0x1f235, true));
		emojies.add(Emoji.fromCodePoint(0x1f234, true));
		emojies.add(Emoji.fromCodePoint(0x1f232, true));
		emojies.add(Emoji.fromCodePoint(0x1f250, true));
		emojies.add(Emoji.fromCodePoint(0x1f239, true));
		emojies.add(Emoji.fromCodePoint(0x1f23a, true));
		emojies.add(Emoji.fromCodePoint(0x1f236, true));
		emojies.add(Emoji.fromCodePoint(0x1f21a, true));
		emojies.add(Emoji.fromCodePoint(0x1f6bb, true));
		emojies.add(Emoji.fromCodePoint(0x1f6b9, true));
		emojies.add(Emoji.fromCodePoint(0x1f6ba, true));
		emojies.add(Emoji.fromCodePoint(0x1f6bc, true));
		emojies.add(Emoji.fromCodePoint(0x1f6be, true));
		emojies.add(Emoji.fromCodePoint(0x1f6b0, false));
		emojies.add(Emoji.fromCodePoint(0x1f6ae, false));
		emojies.add(Emoji.fromCodePoint(0x1f17f, true));
		emojies.add(Emoji.fromChar((char) 0x267f, true));
		emojies.add(Emoji.fromCodePoint(0x1f6ad, true));
		emojies.add(Emoji.fromCodePoint(0x1f237, true));
		emojies.add(Emoji.fromCodePoint(0x1f238, true));
		emojies.add(Emoji.fromCodePoint(0x1f202, true));
		emojies.add(Emoji.fromChar((char) 0x24c2, true));
		emojies.add(Emoji.fromCodePoint(0x1f6c2, false));
		emojies.add(Emoji.fromCodePoint(0x1f6c4, false));
		emojies.add(Emoji.fromCodePoint(0x1f6c5, false));
		emojies.add(Emoji.fromCodePoint(0x1f6c3, false));
		emojies.add(Emoji.fromCodePoint(0x1f251, true));
		emojies.add(Emoji.fromChar((char) 0x3299, true));
		emojies.add(Emoji.fromChar((char) 0x3297, true));
		emojies.add(Emoji.fromCodePoint(0x1f191, true));
		emojies.add(Emoji.fromCodePoint(0x1f198, true));
		emojies.add(Emoji.fromCodePoint(0x1f194, true));
		emojies.add(Emoji.fromCodePoint(0x1f6ab, true));
		emojies.add(Emoji.fromCodePoint(0x1f51e, true));
		emojies.add(Emoji.fromCodePoint(0x1f4f5, false));
		emojies.add(Emoji.fromCodePoint(0x1f6af, false));
		emojies.add(Emoji.fromCodePoint(0x1f6b1, false));
		emojies.add(Emoji.fromCodePoint(0x1f6b3, false));
		emojies.add(Emoji.fromCodePoint(0x1f6b7, false));
		emojies.add(Emoji.fromCodePoint(0x1f6b8, false));
		emojies.add(Emoji.fromChar((char) 0x26d4, true));
		emojies.add(Emoji.fromChar((char) 0x2733, true));
		emojies.add(Emoji.fromChar((char) 0x2747, true));
		emojies.add(Emoji.fromChar((char) 0x274e, true));
		emojies.add(Emoji.fromChar((char) 0x2705, true));
		emojies.add(Emoji.fromChar((char) 0x2734, true));
		emojies.add(Emoji.fromCodePoint(0x1f49f, true));
		emojies.add(Emoji.fromCodePoint(0x1f19a, true));
		emojies.add(Emoji.fromCodePoint(0x1f4f3, true));
		emojies.add(Emoji.fromCodePoint(0x1f4f4, true));
		emojies.add(Emoji.fromCodePoint(0x1f170, true));
		emojies.add(Emoji.fromCodePoint(0x1f171, true));
		emojies.add(Emoji.fromCodePoint(0x1f18e, true));
		emojies.add(Emoji.fromCodePoint(0x1f17e, true));
		emojies.add(Emoji.fromCodePoint(0x1f4a0, true));
		emojies.add(Emoji.fromChar((char) 0x27bf, true));
		emojies.add(Emoji.fromChar((char) 0x267b, true));
		emojies.add(Emoji.fromChar((char) 0x2648, true));
		emojies.add(Emoji.fromChar((char) 0x2649, true));
		emojies.add(Emoji.fromChar((char) 0x264a, true));
		emojies.add(Emoji.fromChar((char) 0x264b, true));
		emojies.add(Emoji.fromChar((char) 0x264c, true));
		emojies.add(Emoji.fromChar((char) 0x264d, true));
		emojies.add(Emoji.fromChar((char) 0x264e, true));
		emojies.add(Emoji.fromChar((char) 0x264f, true));
		emojies.add(Emoji.fromChar((char) 0x2650, true));
		emojies.add(Emoji.fromChar((char) 0x2651, true));
		emojies.add(Emoji.fromChar((char) 0x2652, true));
		emojies.add(Emoji.fromChar((char) 0x2653, true));
		emojies.add(Emoji.fromChar((char) 0x26ce, true));
		emojies.add(Emoji.fromCodePoint(0x1f52f, true));
		emojies.add(Emoji.fromCodePoint(0x1f3e7, true));
		emojies.add(Emoji.fromCodePoint(0x1f4b9, true));
		emojies.add(Emoji.fromCodePoint(0x1f4b2, true));
		emojies.add(Emoji.fromCodePoint(0x1f4b1, true));
		emojies.add(Emoji.fromChar((char) 0x00A9, true));
		emojies.add(Emoji.fromChar((char) 0x00AE, true));
		emojies.add(Emoji.fromChar((char) 0x2122, true));
		emojies.add(Emoji.fromChar((char) 0x274c, true));
		emojies.add(Emoji.fromChar((char) 0x203c, true));
		emojies.add(Emoji.fromChar((char) 0x2049, true));
		emojies.add(Emoji.fromChar((char) 0x2757, true));
		emojies.add(Emoji.fromChar((char) 0x2753, true));
		emojies.add(Emoji.fromChar((char) 0x2755, true));
		emojies.add(Emoji.fromChar((char) 0x2754, true));
		emojies.add(Emoji.fromChar((char) 0x2b55, true));
		emojies.add(Emoji.fromCodePoint(0x1f51d, true));
		emojies.add(Emoji.fromCodePoint(0x1f51a, true));
		emojies.add(Emoji.fromCodePoint(0x1f519, true));
		emojies.add(Emoji.fromCodePoint(0x1f51b, true));
		emojies.add(Emoji.fromCodePoint(0x1f51c, true));
		emojies.add(Emoji.fromCodePoint(0x1f503, true));
		emojies.add(Emoji.fromCodePoint(0x1f55b, true));
		emojies.add(Emoji.fromCodePoint(0x1f567, false));
		emojies.add(Emoji.fromCodePoint(0x1f550, true));
		emojies.add(Emoji.fromCodePoint(0x1f55c, false));
		emojies.add(Emoji.fromCodePoint(0x1f551, true));
		emojies.add(Emoji.fromCodePoint(0x1f55d, false));
		emojies.add(Emoji.fromCodePoint(0x1f552, true));
		emojies.add(Emoji.fromCodePoint(0x1f55e, false));
		emojies.add(Emoji.fromCodePoint(0x1f553, true));
		emojies.add(Emoji.fromCodePoint(0x1f55f, false));
		emojies.add(Emoji.fromCodePoint(0x1f554, true));
		emojies.add(Emoji.fromCodePoint(0x1f560, false));
		emojies.add(Emoji.fromCodePoint(0x1f555, true));
		emojies.add(Emoji.fromCodePoint(0x1f556, true));
		emojies.add(Emoji.fromCodePoint(0x1f557, true));
		emojies.add(Emoji.fromCodePoint(0x1f558, true));
		emojies.add(Emoji.fromCodePoint(0x1f559, true));
		emojies.add(Emoji.fromCodePoint(0x1f55a, true));
		emojies.add(Emoji.fromCodePoint(0x1f561, false));
		emojies.add(Emoji.fromCodePoint(0x1f562, false));
		emojies.add(Emoji.fromCodePoint(0x1f563, false));
		emojies.add(Emoji.fromCodePoint(0x1f564, false));
		emojies.add(Emoji.fromCodePoint(0x1f565, false));
		emojies.add(Emoji.fromCodePoint(0x1f566, false));
		emojies.add(Emoji.fromChar((char) 0x2716, true));
		emojies.add(Emoji.fromChar((char) 0x2795, true));
		emojies.add(Emoji.fromChar((char) 0x2796, true));
		emojies.add(Emoji.fromChar((char) 0x2797, true));
		emojies.add(Emoji.fromChar((char) 0x2660, true));
		emojies.add(Emoji.fromChar((char) 0x2665, true));
		emojies.add(Emoji.fromChar((char) 0x2663, true));
		emojies.add(Emoji.fromChar((char) 0x2666, true));
		emojies.add(Emoji.fromCodePoint(0x1f4ae, true));
		emojies.add(Emoji.fromCodePoint(0x1f4af, true));
		emojies.add(Emoji.fromChar((char) 0x2714, true));
		emojies.add(Emoji.fromChar((char) 0x2611, false));
		emojies.add(Emoji.fromCodePoint(0x1f518, true));
		emojies.add(Emoji.fromCodePoint(0x1f517, true));
		emojies.add(Emoji.fromChar((char) 0x27b0, true));
		emojies.add(Emoji.fromChar((char) 0x3030, true));
		emojies.add(Emoji.fromChar((char) 0x303d, true));
		emojies.add(Emoji.fromCodePoint(0x1f531, true));
		emojies.add(Emoji.fromChar((char) 0x25fc, true));
		emojies.add(Emoji.fromChar((char) 0x25fb, true));
		emojies.add(Emoji.fromChar((char) 0x25fe, true));
		emojies.add(Emoji.fromChar((char) 0x25fd, true));
		emojies.add(Emoji.fromChar((char) 0x25aa, true));
		emojies.add(Emoji.fromChar((char) 0x25ab, true));
		emojies.add(Emoji.fromCodePoint(0x1f53a, true));
		emojies.add(Emoji.fromCodePoint(0x1f532, true));
		emojies.add(Emoji.fromCodePoint(0x1f533, true));
		emojies.add(Emoji.fromChar((char) 0x26ab, true));
		emojies.add(Emoji.fromChar((char) 0x26aa, true));
		emojies.add(Emoji.fromCodePoint(0x1f534, true));
		emojies.add(Emoji.fromCodePoint(0x1f535, true));
		emojies.add(Emoji.fromCodePoint(0x1f53b, true));
		emojies.add(Emoji.fromChar((char) 0x2b1c, true));
		emojies.add(Emoji.fromChar((char) 0x2b1b, true));
		emojies.add(Emoji.fromCodePoint(0x1f536, true));
		emojies.add(Emoji.fromCodePoint(0x1f537, true));
		emojies.add(Emoji.fromCodePoint(0x1f538, true));
		emojies.add(Emoji.fromCodePoint(0x1f539, true));

		emojies.get(0).setSupportedPre21(false);
		emojies.get(1).setSupportedPre21(false);
		emojies.get(2).setSupportedPre21(false);
		emojies.get(3).setSupportedPre21(false);

		emojies.get(4).setSupportedPre21(false);

		emojies.get(5).setSupportedPre21(false);
		emojies.get(6).setSupportedPre21(false);
		emojies.get(7).setSupportedPre21(false);
		emojies.get(8).setSupportedPre21(false);
		emojies.get(9).setSupportedPre21(false);
		emojies.get(12).setSupportedPre21(false);
*/
		return emojies;
	}
}
