package it.keybeeproject.keybee.model;

import java.util.ArrayList;

/**
 * Created by c214 on 27/06/17.
 */

public class EmojiFlag {

    public static final String A = "\uD83C\uDDE6";
    public static final String B = "\uD83C\uDDE7";
    public static final String C = "\uD83C\uDDE8";
    public static final String D = "\uD83C\uDDE9";
    public static final String E = "\uD83C\uDDEA";
    public static final String F = "\uD83C\uDDEB";
    public static final String G = "\uD83C\uDDEC";
    public static final String H = "\uD83C\uDDED";
    public static final String I = "\uD83C\uDDEE";
    public static final String J = "\uD83C\uDDEF";
    public static final String K = "\uD83C\uDDF0";
    public static final String L = "\uD83C\uDDEE";
    public static final String M = "\uD83C\uDDF2";
    public static final String N = "\uD83C\uDDF3";
    public static final String O = "\uD83C\uDDF4";
    public static final String P = "\uD83C\uDDF5";
    public static final String Q = "\uD83C\uDDF6";
    public static final String R = "\uD83C\uDDF7";
    public static final String S = "\uD83C\uDDF8";
    public static final String T = "\uD83C\uDDF9";
    public static final String U = "\uD83C\uDDFA";
    public static final String V = "\uD83C\uDDFB";
    public static final String W = "\uD83C\uDDFC";
    public static final String X = "\uD83C\uDDFD";
    public static final String Y = "\uD83C\uDDFE";
    public static final String Z = "\uD83C\uDDFF";

    //public static final String[] FLAG_CHAR = {A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z};

    public static ArrayList<Emoji> getEmojies() {
        ArrayList<Emoji> emojies = new ArrayList<>();
        emojies.add(Emoji.fromString(("\ud83c\udfe7"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udeae"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udeb0"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\u267f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udeb9"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udeba"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udebb"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udebc"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udebe"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udec2"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udec3"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udec4"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udec5"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\u26a0\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udeb8"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\u26d4"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udeab"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udeb3"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udead"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udeaf"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udeb1"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udeb7"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udcf5"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udd1e"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2622\ufe0f"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2623\ufe0f"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2b06\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2197\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u27a1\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2198\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2b07\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2199\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2b05\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2196\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2195\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2194\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u21a9\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u21aa\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2934\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2935\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udd03"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udd04"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udd19"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udd1a"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udd1b"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udd1c"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udd1d"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\uded0"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\u269b\ufe0f"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udd49\ufe0f"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2721\ufe0f"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2638\ufe0f"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\u262f\ufe0f"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\u271d\ufe0f"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2626\ufe0f"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\u262a\ufe0f"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\u262e\ufe0f"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udd4e"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udd2f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2648"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2649"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u264a"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u264b"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u264c"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u264d"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u264e"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u264f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2650"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2651"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2652"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2653"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u26ce"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udd00"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udd01"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udd02"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\u25b6\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u23e9"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u23ed\ufe0f"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\u23ef\ufe0f"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\u25c0\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u23ea"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u23ee\ufe0f"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udd3c"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u23eb"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udd3d"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u23ec"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u23f8\ufe0f"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\u23f9\ufe0f"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\u23fa\ufe0f"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\u23cf\ufe0f"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udfa6"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udd05"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udd06"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udcf6"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udcf3"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udcf4"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2640\ufe0f"),false,false,false,true,true,true));
        emojies.add(Emoji.fromString(("\u2642\ufe0f"),false,false,false,true,true,true));
        emojies.add(Emoji.fromString(("\u26a7\ufe0f"),false,false,false,false,false,true));
        emojies.add(Emoji.fromString(("\u2716\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2795"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2796"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2797"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u267e\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u203c\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2049\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2753"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2754"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2755"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2757"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u3030\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udcb1"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udcb2"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2695\ufe0f"),false,false,false,true,true,true));
        emojies.add(Emoji.fromString(("\u267b\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u269c\ufe0f"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udd31"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udcdb"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udd30"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2b55"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2705"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2611\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2714\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u274c"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u274e"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u27b0"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u27bf"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\u303d\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2733\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2734\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2747\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u00a9\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u00ae\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2122\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u0023\ufe0f\u20e3"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u002a\ufe0f\u20e3"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\u0030\ufe0f\u20e3"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u0031\ufe0f\u20e3"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u0032\ufe0f\u20e3"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u0033\ufe0f\u20e3"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u0034\ufe0f\u20e3"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u0035\ufe0f\u20e3"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u0036\ufe0f\u20e3"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u0037\ufe0f\u20e3"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u0038\ufe0f\u20e3"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u0039\ufe0f\u20e3"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udd1f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udd20"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udd21"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udd22"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udd23"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udd24"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udd70\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udd8e"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udd71\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udd91"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udd92"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udd93"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2139\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udd94"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u24c2\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udd95"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udd96"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udd7e\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udd97"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udd7f\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udd98"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udd99"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udd9a"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\ude01"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\ude02\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\ude37\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\ude36"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\ude2f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\ude50"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\ude39"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\ude1a"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\ude32"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\ude51"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\ude38"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\ude34"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\ude33"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u3297\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u3299\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\ude3a"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\ude35"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udd34"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udfe0"),false,false,false,false,false,true));
        emojies.add(Emoji.fromString(("\ud83d\udfe1"),false,false,false,false,false,true));
        emojies.add(Emoji.fromString(("\ud83d\udfe2"),false,false,false,false,false,true));
        emojies.add(Emoji.fromString(("\ud83d\udd35"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udfe3"),false,false,false,false,false,true));
        emojies.add(Emoji.fromString(("\ud83d\udfe4"),false,false,false,false,false,true));
        emojies.add(Emoji.fromString(("\u26ab"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u26aa"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udfe5"),false,false,false,false,false,true));
        emojies.add(Emoji.fromString(("\ud83d\udfe7"),false,false,false,false,false,true));
        emojies.add(Emoji.fromString(("\ud83d\udfe8"),false,false,false,false,false,true));
        emojies.add(Emoji.fromString(("\ud83d\udfe9"),false,false,false,false,false,true));
        emojies.add(Emoji.fromString(("\ud83d\udfe6"),false,false,false,false,false,true));
        emojies.add(Emoji.fromString(("\ud83d\udfea"),false,false,false,false,false,true));
        emojies.add(Emoji.fromString(("\ud83d\udfeb"),false,false,false,false,false,true));
        emojies.add(Emoji.fromString(("\u2b1b"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u2b1c"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u25fc\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u25fb\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u25fe"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u25fd"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u25aa\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\u25ab\ufe0f"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udd36"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udd37"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udd38"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udd39"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udd3a"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udd3b"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udca0"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udd18"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udd33"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udd32"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udfc1"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83d\udea9"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udf8c"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udff4"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udff3\ufe0f"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udff3\ufe0f\u200d\ud83c\udf08"),false,false,false,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udff3\ufe0f\u200d\u26a7\ufe0f"),false,false,false,false,false,true));
        emojies.add(Emoji.fromString(("\ud83c\udff4\u200d\u2620\ufe0f"),false,false,false,false,false,true));
        emojies.add(Emoji.fromString(("\ud83c\udde6\ud83c\udde8"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde6\ud83c\udde9"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde6\ud83c\uddea"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde6\ud83c\uddeb"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde6\ud83c\uddec"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde6\ud83c\uddee"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde6\ud83c\uddf1"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde6\ud83c\uddf2"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde6\ud83c\uddf4"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde6\ud83c\uddf6"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde6\ud83c\uddf7"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde6\ud83c\uddf8"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde6\ud83c\uddf9"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde6\ud83c\uddfa"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde6\ud83c\uddfc"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde6\ud83c\uddfd"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde6\ud83c\uddff"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde7\ud83c\udde6"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde7\ud83c\udde7"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde7\ud83c\udde9"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde7\ud83c\uddea"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde7\ud83c\uddeb"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde7\ud83c\uddec"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde7\ud83c\udded"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde7\ud83c\uddee"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde7\ud83c\uddef"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde7\ud83c\uddf1"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde7\ud83c\uddf2"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde7\ud83c\uddf3"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde7\ud83c\uddf4"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde7\ud83c\uddf6"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde7\ud83c\uddf7"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde7\ud83c\uddf8"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde7\ud83c\uddf9"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde7\ud83c\uddfb"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde7\ud83c\uddfc"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde7\ud83c\uddfe"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde7\ud83c\uddff"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde8\ud83c\udde6"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde8\ud83c\udde8"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde8\ud83c\udde9"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde8\ud83c\uddeb"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde8\ud83c\uddec"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde8\ud83c\udded"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde8\ud83c\uddee"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde8\ud83c\uddf0"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde8\ud83c\uddf1"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde8\ud83c\uddf2"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde8\ud83c\uddf3"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde8\ud83c\uddf4"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde8\ud83c\uddf5"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde8\ud83c\uddf7"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde8\ud83c\uddfa"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde8\ud83c\uddfb"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde8\ud83c\uddfc"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde8\ud83c\uddfd"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde8\ud83c\uddfe"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde8\ud83c\uddff"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde9\ud83c\uddea"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde9\ud83c\uddec"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde9\ud83c\uddef"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde9\ud83c\uddf0"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde9\ud83c\uddf2"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde9\ud83c\uddf4"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udde9\ud83c\uddff"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddea\ud83c\udde6"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddea\ud83c\udde8"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddea\ud83c\uddea"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddea\ud83c\uddec"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddea\ud83c\udded"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddea\ud83c\uddf7"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddea\ud83c\uddf8"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddea\ud83c\uddf9"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddea\ud83c\uddfa"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddeb\ud83c\uddee"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddeb\ud83c\uddef"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddeb\ud83c\uddf0"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddeb\ud83c\uddf2"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddeb\ud83c\uddf4"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddeb\ud83c\uddf7"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddec\ud83c\udde6"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddec\ud83c\udde7"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddec\ud83c\udde9"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddec\ud83c\uddea"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddec\ud83c\uddeb"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddec\ud83c\uddec"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddec\ud83c\udded"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddec\ud83c\uddee"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddec\ud83c\uddf1"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddec\ud83c\uddf2"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddec\ud83c\uddf3"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddec\ud83c\uddf5"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddec\ud83c\uddf6"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddec\ud83c\uddf7"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddec\ud83c\uddf8"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddec\ud83c\uddf9"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddec\ud83c\uddfa"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddec\ud83c\uddfc"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddec\ud83c\uddfe"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udded\ud83c\uddf0"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udded\ud83c\uddf2"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udded\ud83c\uddf3"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udded\ud83c\uddf7"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udded\ud83c\uddf9"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udded\ud83c\uddfa"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddee\ud83c\udde8"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddee\ud83c\udde9"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddee\ud83c\uddea"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddee\ud83c\uddf1"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddee\ud83c\uddf2"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddee\ud83c\uddf3"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddee\ud83c\uddf4"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddee\ud83c\uddf6"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddee\ud83c\uddf7"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddee\ud83c\uddf8"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddee\ud83c\uddf9"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddef\ud83c\uddea"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddef\ud83c\uddf2"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddef\ud83c\uddf4"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddef\ud83c\uddf5"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf0\ud83c\uddea"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf0\ud83c\uddec"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf0\ud83c\udded"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf0\ud83c\uddee"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf0\ud83c\uddf2"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf0\ud83c\uddf3"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf0\ud83c\uddf5"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf0\ud83c\uddf7"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf0\ud83c\uddfc"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf0\ud83c\uddfe"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf0\ud83c\uddff"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf1\ud83c\udde6"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf1\ud83c\udde7"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf1\ud83c\udde8"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf1\ud83c\uddee"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf1\ud83c\uddf0"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf1\ud83c\uddf7"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf1\ud83c\uddf8"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf1\ud83c\uddf9"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf1\ud83c\uddfa"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf1\ud83c\uddfb"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf1\ud83c\uddfe"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf2\ud83c\udde6"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf2\ud83c\udde8"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf2\ud83c\udde9"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf2\ud83c\uddea"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf2\ud83c\uddeb"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf2\ud83c\uddec"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf2\ud83c\udded"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf2\ud83c\uddf0"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf2\ud83c\uddf1"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf2\ud83c\uddf2"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf2\ud83c\uddf3"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf2\ud83c\uddf4"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf2\ud83c\uddf5"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf2\ud83c\uddf6"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf2\ud83c\uddf7"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf2\ud83c\uddf8"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf2\ud83c\uddf9"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf2\ud83c\uddfa"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf2\ud83c\uddfb"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf2\ud83c\uddfc"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf2\ud83c\uddfd"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf2\ud83c\uddfe"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf2\ud83c\uddff"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf3\ud83c\udde6"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf3\ud83c\udde8"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf3\ud83c\uddea"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf3\ud83c\uddeb"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf3\ud83c\uddec"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf3\ud83c\uddee"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf3\ud83c\uddf1"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf3\ud83c\uddf4"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf3\ud83c\uddf5"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf3\ud83c\uddf7"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf3\ud83c\uddfa"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf3\ud83c\uddff"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf4\ud83c\uddf2"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf5\ud83c\udde6"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf5\ud83c\uddea"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf5\ud83c\uddeb"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf5\ud83c\uddec"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf5\ud83c\udded"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf5\ud83c\uddf0"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf5\ud83c\uddf1"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf5\ud83c\uddf2"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf5\ud83c\uddf3"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf5\ud83c\uddf7"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf5\ud83c\uddf8"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf5\ud83c\uddf9"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf5\ud83c\uddfc"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf5\ud83c\uddfe"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf6\ud83c\udde6"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf7\ud83c\uddea"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf7\ud83c\uddf4"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf7\ud83c\uddf8"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf7\ud83c\uddfa"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf7\ud83c\uddfc"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf8\ud83c\udde6"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf8\ud83c\udde7"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf8\ud83c\udde8"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf8\ud83c\udde9"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf8\ud83c\uddea"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf8\ud83c\uddec"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf8\ud83c\udded"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf8\ud83c\uddee"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf8\ud83c\uddef"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf8\ud83c\uddf0"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf8\ud83c\uddf1"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf8\ud83c\uddf2"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf8\ud83c\uddf3"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf8\ud83c\uddf4"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf8\ud83c\uddf7"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf8\ud83c\uddf8"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf8\ud83c\uddf9"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf8\ud83c\uddfb"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf8\ud83c\uddfd"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf8\ud83c\uddfe"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf8\ud83c\uddff"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf9\ud83c\udde6"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf9\ud83c\udde8"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf9\ud83c\udde9"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf9\ud83c\uddeb"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf9\ud83c\uddec"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf9\ud83c\udded"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf9\ud83c\uddef"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf9\ud83c\uddf0"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf9\ud83c\uddf1"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf9\ud83c\uddf2"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf9\ud83c\uddf3"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf9\ud83c\uddf4"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf9\ud83c\uddf7"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf9\ud83c\uddf9"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf9\ud83c\uddfb"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf9\ud83c\uddfc"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddf9\ud83c\uddff"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddfa\ud83c\udde6"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddfa\ud83c\uddec"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddfa\ud83c\uddf2"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddfa\ud83c\uddf3"),false,false,false,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddfa\ud83c\uddf8"),true,true,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddfa\ud83c\uddfe"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddfa\ud83c\uddff"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddfb\ud83c\udde6"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddfb\ud83c\udde8"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddfb\ud83c\uddea"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddfb\ud83c\uddec"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddfb\ud83c\uddee"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddfb\ud83c\uddf3"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddfb\ud83c\uddfa"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddfc\ud83c\uddeb"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddfc\ud83c\uddf8"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddfd\ud83c\uddf0"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddfe\ud83c\uddea"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddfe\ud83c\uddf9"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddff\ud83c\udde6"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddff\ud83c\uddf2"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\uddff\ud83c\uddfc"),false,false,true,true,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udff4\udb40\udc67\udb40\udc62\udb40\udc65\udb40\udc6e\udb40\udc67\udb40\udc7f"),false,false,false,false,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udff4\udb40\udc67\udb40\udc62\udb40\udc73\udb40\udc63\udb40\udc74\udb40\udc7f"),false,false,false,false,true,true));
        emojies.add(Emoji.fromString(("\ud83c\udff4\udb40\udc67\udb40\udc62\udb40\udc77\udb40\udc6c\udb40\udc73\udb40\udc7f"),false,false,false,false,true,true));








       /* emojies.add(Emoji.fromCodePoint(0x1f38c, true));
        emojies.add(Emoji.fromCodePoint(0x1f3c1, true));
        emojies.add(Emoji.fromCodePoint(0x1f6a9, true));
        emojies.add(Emoji.fromString(C + N, false, false));
        emojies.add(Emoji.fromString(D + E, false, false));
        emojies.add(Emoji.fromString(E + S, false, false));
        emojies.add(Emoji.fromString(F + R, false, false));
        emojies.add(Emoji.fromString(I + T, false, false));
        emojies.add(Emoji.fromString(J + P, false, false));
        emojies.add(Emoji.fromString(K + R, false, false));
        emojies.add(Emoji.fromString(R + U, false, false));
        emojies.add(Emoji.fromString(U + S, false, false));
        emojies.add(Emoji.fromString(A + D, false, false));
        emojies.add(Emoji.fromString(A + E, false, false));
        emojies.add(Emoji.fromString(A + F, false, false));
        emojies.add(Emoji.fromString(A + G, false, false));
        emojies.add(Emoji.fromString(A + L, false, false));
        emojies.add(Emoji.fromString(A + M, false, false));
        emojies.add(Emoji.fromString(A + O, false, false));
        emojies.add(Emoji.fromString(A + R, false, false));
        emojies.add(Emoji.fromString(A + S, false, false));
        emojies.add(Emoji.fromString(A + T, false, false));
        emojies.add(Emoji.fromString(A + U, false, false));
        emojies.add(Emoji.fromString(A + W, false, false));
        emojies.add(Emoji.fromString(A + X, false, false));
        emojies.add(Emoji.fromString(A + Z, false, false));
        emojies.add(Emoji.fromString(B + A, false, false));
        emojies.add(Emoji.fromString(B + B, false, false));
        emojies.add(Emoji.fromString(B + D, false, false));
        emojies.add(Emoji.fromString(B + E, false, false));
        emojies.add(Emoji.fromString(B + F, false, false));
        emojies.add(Emoji.fromString(B + G, false, false));
        emojies.add(Emoji.fromString(B + H, false, false));
        //emojies.add(Emoji.fromString(B + I, false, false));
        emojies.add(Emoji.fromString(B + J, false, false));
        emojies.add(Emoji.fromString(B + L, false, false));
        emojies.add(Emoji.fromString(B + M, false, false));
        emojies.add(Emoji.fromString(B + N, false, false));
        emojies.add(Emoji.fromString(B + O, false, false));
        emojies.add(Emoji.fromString(B + R, false, false));
        emojies.add(Emoji.fromString(B + S, false, false));
        emojies.add(Emoji.fromString(B + T, false, false));
        emojies.add(Emoji.fromString(B + W, false, false));
        emojies.add(Emoji.fromString(B + Y, false, false));
        emojies.add(Emoji.fromString(B + Z, false, false));
        emojies.add(Emoji.fromString(C + A, false, false));
        emojies.add(Emoji.fromString(C + C, false, false));
        emojies.add(Emoji.fromString(C + D, false, false));
        emojies.add(Emoji.fromString(C + F, false, false));
        emojies.add(Emoji.fromString(C + G, false, false));
        emojies.add(Emoji.fromString(C + H, false, false));
        emojies.add(Emoji.fromString(C + I, false, false));
        emojies.add(Emoji.fromString(C + K, false, false));
        emojies.add(Emoji.fromString(C + L, false, false));
        emojies.add(Emoji.fromString(C + M, false, false));
        emojies.add(Emoji.fromString(C + N, false, false));
        emojies.add(Emoji.fromString(C + O, false, false));
        emojies.add(Emoji.fromString(C + R, false, false));
        emojies.add(Emoji.fromString(C + U, false, false));
        emojies.add(Emoji.fromString(C + V, false, false));
        emojies.add(Emoji.fromString(C + W, false, false));
        emojies.add(Emoji.fromString(C + X, false, false));
        emojies.add(Emoji.fromString(C + Y, false, false));
        emojies.add(Emoji.fromString(C + Z, false, false));
        emojies.add(Emoji.fromString(D + E, false, false));
        emojies.add(Emoji.fromString(D + J, false, false));
        emojies.add(Emoji.fromString(D + K, false, false));
        emojies.add(Emoji.fromString(D + M, false, false));
        emojies.add(Emoji.fromString(D + O, false, false));
        emojies.add(Emoji.fromString(D + Z, false, false));
        emojies.add(Emoji.fromString(E + C, false, false));
        emojies.add(Emoji.fromString(E + E, false, false));
        emojies.add(Emoji.fromString(E + G, false, false));
        emojies.add(Emoji.fromString(E + R, false, false));
        emojies.add(Emoji.fromString(E + S, false, false));
        emojies.add(Emoji.fromString(E + T, false, false));
        emojies.add(Emoji.fromString(F + I, false, false));
        emojies.add(Emoji.fromString(F + J, false, false));
        emojies.add(Emoji.fromString(F + M, false, false));
        emojies.add(Emoji.fromString(F + O, false, false));
        emojies.add(Emoji.fromString(F + R, false, false));
        emojies.add(Emoji.fromString(G + A, false, false));
        emojies.add(Emoji.fromString(G + B, false, false));
        emojies.add(Emoji.fromString(G + D, false, false));
        emojies.add(Emoji.fromString(G + E, false, false));
        emojies.add(Emoji.fromString(G + G, false, false));
        emojies.add(Emoji.fromString(G + H, false, false));
        emojies.add(Emoji.fromString(G + I, false, false));
        emojies.add(Emoji.fromString(G + L, false, false));
        emojies.add(Emoji.fromString(G + M, false, false));
        emojies.add(Emoji.fromString(G + N, false, false));
        emojies.add(Emoji.fromString(G + Q, false, false));
        emojies.add(Emoji.fromString(G + R, false, false));
        emojies.add(Emoji.fromString(G + T, false, false));
        emojies.add(Emoji.fromString(G + U, false, false));
        emojies.add(Emoji.fromString(G + W, false, false));
        emojies.add(Emoji.fromString(G + Y, false, false));
        emojies.add(Emoji.fromString(H + K, false, false));
        emojies.add(Emoji.fromString(H + N, false, false));
        emojies.add(Emoji.fromString(H + R, false, false));
        emojies.add(Emoji.fromString(H + T, false, false));
        emojies.add(Emoji.fromString(H + U, false, false));
        emojies.add(Emoji.fromString(I + D, false, false));
        emojies.add(Emoji.fromString(I + E, false, false));
        emojies.add(Emoji.fromString(I + M, false, false));
        emojies.add(Emoji.fromString(I + N, false, false));
        emojies.add(Emoji.fromString(I + O, false, false));
        emojies.add(Emoji.fromString(I + Q, false, false));
        emojies.add(Emoji.fromString(I + R, false, false));
        emojies.add(Emoji.fromString(I + S, false, false));
        emojies.add(Emoji.fromString(I + T, false, false));
        emojies.add(Emoji.fromString(J + E, false, false));
        emojies.add(Emoji.fromString(J + M, false, false));
        emojies.add(Emoji.fromString(J + O, false, false));
        emojies.add(Emoji.fromString(J + P, false, false));
        emojies.add(Emoji.fromString(K + E, false, false));
        emojies.add(Emoji.fromString(K + G, false, false));
        emojies.add(Emoji.fromString(K + H, false, false));
        emojies.add(Emoji.fromString(K + I, false, false));
        emojies.add(Emoji.fromString(K + M, false, false));
        emojies.add(Emoji.fromString(K + N, false, false));
        emojies.add(Emoji.fromString(K + P, false, false));
        emojies.add(Emoji.fromString(K + R, false, false));
        emojies.add(Emoji.fromString(K + W, false, false));
        emojies.add(Emoji.fromString(K + Y, false, false));
        emojies.add(Emoji.fromString(K + Z, false, false));
        emojies.add(Emoji.fromString(L + R, false, false));
        emojies.add(Emoji.fromString(L + T, false, false));
        emojies.add(Emoji.fromString(M + A, false, false));
        emojies.add(Emoji.fromString(M + C, false, false));
        emojies.add(Emoji.fromString(M + D, false, false));
        emojies.add(Emoji.fromString(M + E, false, false));
        emojies.add(Emoji.fromString(M + G, false, false));
        emojies.add(Emoji.fromString(M + H, false, false));
        emojies.add(Emoji.fromString(M + K, false, false));
        emojies.add(Emoji.fromString(M + M, false, false));
        emojies.add(Emoji.fromString(M + N, false, false));
        emojies.add(Emoji.fromString(M + O, false, false));
        emojies.add(Emoji.fromString(M + P, false, false));
        emojies.add(Emoji.fromString(M + R, false, false));
        emojies.add(Emoji.fromString(M + S, false, false));
        emojies.add(Emoji.fromString(M + T, false, false));
        emojies.add(Emoji.fromString(M + U, false, false));
        emojies.add(Emoji.fromString(M + V, false, false));
        emojies.add(Emoji.fromString(M + W, false, false));
        emojies.add(Emoji.fromString(M + X, false, false));
        emojies.add(Emoji.fromString(M + Y, false, false));
        emojies.add(Emoji.fromString(M + Z, false, false));
        emojies.add(Emoji.fromString(N + A, false, false));
        emojies.add(Emoji.fromString(N + E, false, false));
        emojies.add(Emoji.fromString(N + F, false, false));
        emojies.add(Emoji.fromString(N + G, false, false));
        emojies.add(Emoji.fromString(N + L, false, false));
        emojies.add(Emoji.fromString(N + O, false, false));
        emojies.add(Emoji.fromString(N + P, false, false));
        emojies.add(Emoji.fromString(N + R, false, false));
        emojies.add(Emoji.fromString(N + U, false, false));
        emojies.add(Emoji.fromString(N + Z, false, false));
        emojies.add(Emoji.fromString(O + M, false, false));
        emojies.add(Emoji.fromString(P + A, false, false));
        emojies.add(Emoji.fromString(P + E, false, false));
        emojies.add(Emoji.fromString(P + F, false, false));
        emojies.add(Emoji.fromString(P + G, false, false));
        emojies.add(Emoji.fromString(P + H, false, false));
        emojies.add(Emoji.fromString(P + K, false, false));
        emojies.add(Emoji.fromString(P + N, false, false));
        emojies.add(Emoji.fromString(P + R, false, false));
        emojies.add(Emoji.fromString(P + S, false, false));
        emojies.add(Emoji.fromString(P + T, false, false));
        emojies.add(Emoji.fromString(P + W, false, false));
        emojies.add(Emoji.fromString(P + Y, false, false));
        emojies.add(Emoji.fromString(Q + A, false, false));
        emojies.add(Emoji.fromString(R + O, false, false));
        emojies.add(Emoji.fromString(R + S, false, false));
        emojies.add(Emoji.fromString(R + U, false, false));
        emojies.add(Emoji.fromString(R + W, false, false));
        emojies.add(Emoji.fromString(S + A, false, false));
        emojies.add(Emoji.fromString(S + B, false, false));
        emojies.add(Emoji.fromString(S + C, false, false));
        emojies.add(Emoji.fromString(S + D, false, false));
        emojies.add(Emoji.fromString(S + E, false, false));
        emojies.add(Emoji.fromString(S + G, false, false));
        emojies.add(Emoji.fromString(S + K, false, false));
        emojies.add(Emoji.fromString(S + L, false, false));
        emojies.add(Emoji.fromString(S + M, false, false));
        emojies.add(Emoji.fromString(S + N, false, false));
        emojies.add(Emoji.fromString(S + O, false, false));
        emojies.add(Emoji.fromString(S + R, false, false));
        emojies.add(Emoji.fromString(S + S, false, false));
        emojies.add(Emoji.fromString(S + T, false, false));
        emojies.add(Emoji.fromString(S + V, false, false));
        emojies.add(Emoji.fromString(S + X, false, false));
        emojies.add(Emoji.fromString(S + Y, false, false));
        emojies.add(Emoji.fromString(S + Z, false, false));
        emojies.add(Emoji.fromString(T + C, false, false));
        emojies.add(Emoji.fromString(T + D, false, false));
        emojies.add(Emoji.fromString(T + G, false, false));
        emojies.add(Emoji.fromString(T + H, false, false));
        emojies.add(Emoji.fromString(T + J, false, false));
        emojies.add(Emoji.fromString(T + K, false, false));
        emojies.add(Emoji.fromString(T + M, false, false));
        emojies.add(Emoji.fromString(T + N, false, false));
        emojies.add(Emoji.fromString(T + O, false, false));
        emojies.add(Emoji.fromString(T + R, false, false));
        emojies.add(Emoji.fromString(T + T, false, false));
        emojies.add(Emoji.fromString(T + V, false, false));
        emojies.add(Emoji.fromString(T + W, false, false));
        emojies.add(Emoji.fromString(T + Z, false, false));
        emojies.add(Emoji.fromString(U + A, false, false));
        emojies.add(Emoji.fromString(U + G, false, false));
        emojies.add(Emoji.fromString(U + S, false, false));
        emojies.add(Emoji.fromString(U + Y, false, false));
        emojies.add(Emoji.fromString(U + Z, false, false));
        emojies.add(Emoji.fromString(V + A, false, false));
        emojies.add(Emoji.fromString(V + C, false, false));
        emojies.add(Emoji.fromString(V + E, false, false));
        emojies.add(Emoji.fromString(V + G, false, false));
        emojies.add(Emoji.fromString(V + I, false, false));
        emojies.add(Emoji.fromString(V + N, false, false));
        emojies.add(Emoji.fromString(V + U, false, false));
        emojies.add(Emoji.fromString(W + S, false, false));
        emojies.add(Emoji.fromString(Y + E, false, false));
        emojies.add(Emoji.fromString(Z + A, false, false));
        emojies.add(Emoji.fromString(Z + M, false, false));
        emojies.add(Emoji.fromString(Z + W, false, false));
        emojies.add(Emoji.fromString("\uD83C\uDDF3\uD83C\uDDF1", false, false));
*/
        //emojies.add(Emoji.fromString(L + S, false, false));
        //emojies.add(Emoji.fromString(S + I, false, false));
        //emojies.add(Emoji.fromString(N + I, false, false));
        //emojies.add(Emoji.fromString(G + B, false, false));
        //emojies.add(Emoji.fromString(A + I, false, false));

        //emojies.add(Emoji.fromCodePoint(0x1f308, true));

        /*emojies.add(Emoji.fromCodePoint(0x1f1e6, true));
        emojies.add(Emoji.fromCodePoint(0x1f1fd, true));
        emojies.add(Emoji.fromCodePoint(0x1f1f1, true));
        emojies.add(Emoji.fromCodePoint(0x1f1eb, true));
        emojies.add(Emoji.fromCodePoint(0x1f1ff, true));
        emojies.add(Emoji.fromCodePoint(0x1f1e9, true));
        emojies.add(Emoji.fromCodePoint(0x1f1f4, true));
        emojies.add(Emoji.fromCodePoint(0x1f1ee, true));
        emojies.add(Emoji.fromCodePoint(0x1f1f6, true));
        emojies.add(Emoji.fromCodePoint(0x1f1ec, true));
        emojies.add(Emoji.fromCodePoint(0x1f1f7, true));
        emojies.add(Emoji.fromCodePoint(0x1f1f2, true));
        emojies.add(Emoji.fromCodePoint(0x1f1fc, true));
        emojies.add(Emoji.fromCodePoint(0x1f1f9, true));
        emojies.add(Emoji.fromCodePoint(0x1f1f8, true));
        emojies.add(Emoji.fromCodePoint(0x1f1ed, true));
        emojies.add(Emoji.fromCodePoint(0x1f1e7, true));
        emojies.add(Emoji.fromCodePoint(0x1f1fe, true));
        emojies.add(Emoji.fromCodePoint(0x1f1ea, true));
        emojies.add(Emoji.fromCodePoint(0x1f1ef, true));
        emojies.add(Emoji.fromCodePoint(0x1f1fb, true));
        emojies.add(Emoji.fromCodePoint(0x1f1f3, true));
        emojies.add(Emoji.fromCodePoint(0x1f1e8, true));
        emojies.add(Emoji.fromCodePoint(0x1f1fa, true));
        emojies.add(Emoji.fromCodePoint(0x1f1f5, true));
        emojies.add(Emoji.fromCodePoint(0x1f1f0, true));*/

        return emojies;
    }
}
